### ISSUE TITLE
Grainstation-C fails in Tracktion Waveform 11 Beta

### ISSUE THREAD

**Issue by MSB-P** [micah-frank-studio/Prototypes#2]
Greetings Micah,

Thanks for offering your prototypes to play with! I'm not a code geek, yet I'm working with Tracktion Inc. regarding Waveform and related beta testing. As the subject suggests, Waveform is not liking Grainstation-C. Your other prototypes work well in 11 Beta.

I've attached a log file generated by Tracktion's plugin testing app titled PluginVal. It shows the failures, which might be helpful for you to investigate.

Cheers!
Philip

[Grainstation-C.txt](https://github.com/micah-frank-studio/Prototypes/files/4265273/Grainstation-C.txt)

**Comment by micah-frank-studio** [comment]
Hi Philip,

I'm forwarding this to Rory who might be able to help...

**Comment by MSB-P** [comment]
Thanks Micah.

**Comment by rorywalsh** [comment]
Hi @MSB-P I just tried this with Waveform 10 as I can't access 11, but it loaded and ran fine (as you can see below). Can you try the latest [Cabbage beta](https://dev.azure.com/rorywalsh/cabbage/_build/results?buildId=599&view=artifacts&type=publishedArtifacts) for Window. Just click the 'Drop' link and download. Then open Grainstation and export with again. Let me know how it goes ;)   
![image](https://user-images.githubusercontent.com/2689817/75762349-6efc5500-5d32-11ea-9db6-8d4fe2fb20c7.png)

**Comment by MSB-P** [comment]
Hello Rory,
Thanks for responding, and sharing your results with Waveform 10.
I get the same failure when loading Grainstation-C in Waveform 10. Are you running the Mac, or Windows version of Waveform?
I downloaded the Cabbage Beta and installed it, yet was unsure what to do after that. I launched it and tried to create an effect from the Grainstation-C.dll file, which created a Grainstation-C.csd file. I have no clue what I'm doing, thus more explicit instructions would be welcome.
Thanks,
Philip   On Tuesday, March 3, 2020, 3:39:01 AM CST, Rory Walsh <notifications@github.com> wrote:  
 
 
Hi @MSB-P I just tried this with Waveform 10 as I can't access 11, but it loaded and ran fine (as you can see below). Can you try the latest Cabbage beta for Window. Just click the 'Drop' link and download. Then open Grainstation and export with again. Let me know how it goes ;)

**Comment by rorywalsh** [comment]
Apologies, I thought that you had exported the original one in this manner. Best if you clone or download the zip for this repo. Once it's extracted, open the Grainstation-C.csd file from the Prototypes/GrainstationC/ folder. Then go to File->Export->VST->Plugin Synth and name the output file Grainstation-C, you don't need to add an extension. This will create a .dll plugin file. Then add the Prototypes/GrainstationC directory to the list of plugin folders in Waveform and rescan. It should show then. Let me know if it works.

**Comment by MSB-P** [comment]
Thanks for your patience, and good feedback.
I downloaded the zip and simply re-ran the installation file in Win64_GrainstationC_Prototype.zip - Grainstation-C.exe, which has it working in Waveform 11.
Cheers!
P

    On Tuesday, March 3, 2020, 7:26:49 AM CST, Rory Walsh <notifications@github.com> wrote:  
 
 
Apologies, I thought that you had exported the original one in this manner. Best if you clone or download the zip for this repo. Once it's extracted, open the Grainstation-C.csd file from the Prototypes/GrainstationC/ folder. Then go to File->Export->VST->Plugin Synth and name the output file Grainstation-C, you don't need to add an extension. This will create a .dll plugin file. Then add the Prototypes/GrainstationC directory to the list of plugin folders in Waveform and rescan. It should show then. Let me know if it works.

**Comment by micah-frank-studio** [comment]
Great... Thanks for helping out Rory!

**Comment by MSB-P** [comment]
Ditto on the thanks to Rory!
Grainstation is cool, yet hammers my lowly dual core laptop's CPU utilization.  :|
Be cool to have mutes for the channels, and pan control.
Installed Echolift, which is an interesting / fun offering.
Again, thanks for sharing theses prototypes!

Gratefully,
Philip   On Tuesday, March 3, 2020, 1:41:42 PM CST, Micah Frank <notifications@github.com> wrote:  
 
 
Great... Thanks for helping out Rory!
