### ISSUE TITLE
Mac OS developer identification

### ISSUE THREAD

**Issue by agawley** [micah-frank-studio/Prototypes#3]
Is there a way to run these plugins on Catalina? I'm getting that annoying prompt about not being able to identify the developer when I try to run them in Ableton. No worries if it is a huge effort for you to make this work (and hence not worth it for prototypes), just wanted to check I wasn't missing something obvious.

**Comment by micah-frank-studio** [comment]
should be fine. You need to ctrl click and select "open" if you have
trouble with the installer - it's in security settings.

**Comment by agawley** [comment]
This was for the VSTs which don't have an installer. Seems like if copy them into my VST folder, then open Ableton, then go to settings and approve them, then close Ableton and reopen Ableton it works. Sometimes MacOS makes me feel like a mouse in a cage doing a dance to get cheese!
